# Generated by Django 5.1 on 2024-09-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
        migrations.AlterModelTable(
            name="task",
            table="tasks",
        ),
    ]
